export const LOAD_PROBLEM_DETAILS_SUCCESS = 'LOAD_PROBLEM_DETAILS_SUCCESS';
export const LOAD_PROBLEM_DETAILS = 'LOAD_PROBLEM_DETAILS';
export const LOAD_PROBLEM_DETAILS_ERROR = 'LOAD_PROBLEM_DETAILS_ERROR';
