export const SUBMIT_PROBLEM_SUCCESS = 'SUBMIT_PROBLEM_SUCCESS';
export const SUBMIT_PROBLEM = 'SUBMIT_PROBLEM';
export const SUBMIT_PROBLEM_ERROR = 'SUBMIT_PROBLEM_ERROR';
export const SUBMIT_PROBLEM_THROTTLE_ERROR = 'SUBMIT_PROBLEM_THROTTLE_ERROR';
export const RESET_PROBLEM_SUBMISSION = 'RESET_PROBLEM_SUBMISSION';
