export const INPUT_TEXT = 'Input (Stdin)'
export const SUBMIT_YOUR_CODE = 'Submit your code'
export const INTERNAL_ERROR = 'Internal Error'
export const SUBMIT_CODE = 'Submit Code'
export const PROCESSING_TEXT = 'Processing...'
