# Be sure to use the correct doppler configurations
version: "3.8"

services:
  box:
    image: ninjaprep/box
  npserver:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    image: ninjaprep/npserver
    environment:
      - DOPPLER_TOKEN
    command: ["doppler", "run", "--", "yarn", "integration-test"]
