#  Dockerfile for Node Express Backend
FROM node:15-alpine
ENV NODE_ENV production

# Create App Directory
WORKDIR /usr/src/app

RUN mkdir client
RUN mkdir server

# Install Dependencies
COPY ./client/package*.json ./client 
COPY ./server/package*.json ./server

WORKDIR /usr/src/app/client
RUN yarn install --silent
COPY ./client ./
RUN yarn build

WORKDIR /usr/src/app/server
COPY ./server ./
RUN yarn install --silent
RUN yarn build

# Exports
EXPOSE 5000

CMD ["yarn","prod"]