version: "3.7"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: ninja-prep-server
    container_name: ninja-prep-server
    command: yarn start
    volumes:
      - ./server/:/usr/src/app
      - ./server/node_modules:/usr/src/app/node_modules
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    networks:
      - app-network
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      CHOKIDAR_USEPOLLING: "true"
      PROXY_DOMAIN: "server"
    image: ninja-prep-client
    container_name: ninja-prep-client
    command: yarn start
    volumes:
      - ./client/:/usr/src/app
      - ./client/node_modules:/usr/src/app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
    stdin_open: true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local
