version: 2.1

orbs:
  node: circleci/node@1.1.6
  codecov: codecov/codecov@1.1.0

jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn global add jest
            - run: yarn test
            - run: sudo yarn global add codecov
            - run: codecov
            - codecov/upload:
                file: ./coverage/coverage-final.json

workflows:
  build-and-test:
    jobs:
      - build-and-test
