version: 2.1

orbs:
  node: circleci/node@3.0.1
  codecov: codecov/codecov@1.1.0

jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
          install-yarn: true
          install-npm: false
          node-version: latest
      - run: 
          name: Adding NPM/Yarn dependencies
          command: sudo chmod +x ./bin/InstallDependencies.sh && sudo ./bin/InstallDependencies.sh
      - run: 
          name: Testing Client Folder
          command: cd client && yarn jest
      - run: 
          name: Client Build Attempt
          command: CI=false yarn --cwd ./client run build
      - run: 
          name: Adding Code Coverage
          command: sudo chmod +x ./bin/CodeCoverageClient.sh && sudo ./bin/CodeCoverageClient.sh
      - codecov/upload:
          file: ./client/coverage/coverage-final.json

  deploy-prod:
    executor:
      name: node/default
    steps:
      - checkout
      - run: 
          name: Deploy to Production
          command: ssh -o StrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP "./deploy_project.sh"

workflows:
  build-and-test:
    jobs:
      - build-and-test
      - deploy-prod:
          filters:
            branches:
              only:
                - master
          requires:
            - build-and-test
